### ISSUE TITLE
Recommend special handling (eg, prohibition) for .arpa and special-use domains

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#102]
We should recommend that special handling may be needed for .arpa as well as special-use domains (https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml).

General guidance may wish to be that validating names within special-use domains as well as .arpa should generally be prohibited unless explicitly defined.

**Comment by paulwouters** [comment]
wouldn't that just fail anyway? Either you own the domain (in the
worldview) or you don't. Why would anything special be needed?

If someone claims ownership of alt.foobar, they would just simply fail to
prove they own it anyway ?
Why is extra text needed?

Paul

**Comment by moonshiner** [comment]
this does not feel needed to wrap up the current version. I'm marking this ready to close.
