### ISSUE TITLE
Give examples for why a PRIVATE entry in the PSL might need to be validated

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#103]
There was some confusion on why a PRIVATE entry in the PSL might need to be validated, so having some more context or an example might be helpful.

Concrete example for domain verification for public suffixes in the PRIVATE division of the PSL:
object storage provider or CDN "Foo" has a structure of <customer>.foo.example so both 
needs foo.example to be on the PSL (eg, so customers can't set cookies on foo.example)
but where the provider Foo themselves need to get a wildcard certificate for "*.foo.example".

(This is the reason for the PRIVATE vs ICANN divisions in the PSL.)

**Comment by ShivanKaul** [comment]
I think this is addressed by https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/blob/main/draft-ietf-dnsop-domain-verification-techniques.md#public-suffixes-public-suffixes

**Comment by moonshiner** [comment]
agreed thanks for confirming
