### ISSUE TITLE
Document risks of splicing prefixes and suffixes in different contexts

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#105]
Daniel Gillmor raises a point at the mic that if people are splicing prefixes and suffixes in different orders that there's a risk that different actors could swap these as an attack.  For example, if we have "_label-token" in one context and "_token-label" in a different context that there might be possibilities for some actor to provide a label as a token.

We should review our usage and perhaps add a security consideration around this.

**Comment by dkg** [comment]
This concern might also be relevant even across a label boundary  (to adapt your example, `_label.token` as well as `token._label`), not necessarily just splicing.  The safest thing seems to be to ensure that the fixed strings ("labels"?) always go second (closer to the root), and peer-supplied challenge tokens always go first (farther from the root), for all protocols that use this pattern.  But i don't know how this protocol can control what other protocols do :grimacing:   What you really want is to make it impossible for a token provider to offer something that, when placed on the wire could be misinterpreted as a label intended for other purposes..

As far as security considerations go, i'd hope that they wouldn't be security considerations for operators, but rather security considerations for all DNS protocols that use a similar pattern.  The zone admin shouldn't need to worry about this.

**Comment by shuque** [comment]
Hey @enygren and @dkg - sorry for being dense, but I need some help understanding the specific threat. So, let's use a specific example. 

The application provider "foobar" wants the user of the "example.com" domain, and one of their accounts "xjbhkrt" on the foobar service to deploy a challenge record in their DNS with the challenge token "ORUGKIDROVUWG2ZAMJZG653OEBTG66AK". 

So the application provider has provided all 3 variables here, account label, application label, and token data:

xjbhkrt._foobar-challenge.example.com. IN TXT "ORUGKIDROVUWG2ZAMJZG653OEBTG66AK"

The application label is closest to the root, and presumably a recognizable string that the user can visually associate with the application provider. The account label and challenge token are more random looking strings. There are no variable prefix & suffixes within the same label.

Can you elaborate on the threat here?

**Comment by ShivanKaul** [comment]
The draft currently says in [5.1.1](https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-domain-verification-techniques-04#section-5.1.1):
```
The RECOMMENDED format is application-specific underscore prefix labels. 
Domain Control Validation records are constructed by the provider by prepending 
the label "_<PROVIDER_RELEVANT_NAME>-challenge" to the domain name 
being validated (e.g. "_foo-challenge.example.com"). 
The prefixed "_" is used to avoid collisions with existing hostnames.
```

It goes on to say in [5.2](https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-domain-verification-techniques-04#name-txt-record):
```
If a provider has an application-specific need to have multiple
verifications for the same label, multiple prefixes can be used:

   _feature1._foo-challenge.example.com.  IN   TXT  "3419...3d206c4"
```

Doesn't that resolve the ordering between the random token and the label? Or is the concern here for CNAME records in the case of delegated domain control validation? For those we say in [5.3.1](https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-domain-verification-techniques-04#section-5.3.1):

```
In this case, the target of the CNAME would contain the base16-encoded 
(or base32-encoded) random token followed by a suffix specified by the provider.
```

**Comment by moonshiner** [comment]
I "believe" the text in -04 addresses the issues here, but I'd prefer a second set of eyes on that.

**Comment by paulwouters** [comment]
We could add a note saying that token values MUST NOT start with an _ to avoid it being interpreted as a _label ?

**Comment by enygren** [comment]
There are some issues with the initial proposal, so re-opened in #138.
#139 at least brings internal consistency (and adds a security consideration) while we address.
For discussion in dnsop.
