### ISSUE TITLE
Reference RFC9444 (ACME for SubDomains) and talk about use-cases

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#106]
RFC9444 (ACME for SubDomains) is an extrapolation of the wildcard vs exact-name use-case.  We may want to suggest that a separate label is used for this (eg, -subdomain) which may be the same one used for wildcards. 

At the same time we may wish to mention that a reason for separate labels is also to allow different ACLs on dynamic DNS updates (for the exact name vs allowing validation of anything under the subdomain), not just for human user visibility.

**Comment by moonshiner** [comment]
We should add a RFC9444 example to this document, as 9444 doesn't explicitly show adding a DNS record for the subdomains, just the parent domain.

**Comment by enygren** [comment]
I think we'll want to reference draft-ietf-acme-dns-account-challenge-01 here which now incorporates these.

**Comment by moonshiner** [comment]
The draft chain

draft-todo-chariton-dns-account-01  =>  draft-ietf-acme-dns-account-01 => draft-ietf-acme-dns-account-challenge-01 =>  draft-ietf-acme-scoped-dns-challenges

ACME-SCOPED-CHALLENGE references the current version

I think this is in there

**Comment by paulwouters** [comment]
It is .
