### ISSUE TITLE
Authors were going to talk to CA/B Forum 

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#114]
Something Something making sure nothing is being missed.

**Comment by shuque** [comment]
Tim - I believe that the plan was for the authors to talk to others that have CAB forum connections to follow-up on this issue. I believe that has already taken place via Tim Hollebeek of Digicert.

Reference: Proposed CAB forum ballot for scoped DNS challenges.
https://github.com/wthayer/servercert/pull/2/files

I think we can proceed with last calling our document and moving it along in the meantime.
