### ISSUE TITLE
Perform a broader review of using "Provider", "provider", and "service provider"

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#120]
As doc shepherd will collect data

**Comment by moonshiner** [comment]
thru some regexp foo

Provider - 7

service provider - 12 

provider (no 'service') - 44

"provider services" - 2 (same paragraph)

**Comment by moonshiner** [comment]
This is my half baked logic:

"service provider" does imply it is a 'provider of a service' though the definition does state this. 
But 'provider' may also imply 'DNS provider' to some

However, we must fix the two "provider services"


Also if we go with Provider, we should 
- convert the 12 'service provider' to 'Provider'
- check each use of 'provider', changing relevant ones to 'Provider'

is this logical?

**Comment by moonshiner** [comment]
in a similar vein, the docuiment uses "application service provider" in most places, except for two where it uses "application provider"

**Comment by paulwouters** [comment]
There are a lot of "service provider" that could/should be "application service provider". but I guess as per our own terminology that could be "Provider". I am just personally a bit concerned that the term "Provider" might not be clear, especially when distinquishing the application service provider from the DNS provider.

So I would like to see "service provider" to be changed to "application service provider". But I can also accept if I am in the rough.

**Comment by moonshiner** [comment]
I agree that "Provider" is too vague.  

I can live with "application service provider" or "service provider", I am not picky.  
But should they be Capitalized ?

**Comment by paulwouters** [comment]
I created https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/124 but before merging, lets get some approval from my co-authors as it is fairly invasive (and subjective)

**Comment by moonshiner** [comment]
I want y'all to consensus on this, but I like where this is going.

**Comment by moonshiner** [comment]
Merged - closing.  

opening new issyue on uses of Intermediary
