### ISSUE TITLE
Inconsistency on guidance of underscore before a token

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#138]
Our current guidance (from #105) on "When placed in a domain name, the token MUST NOT start with an underscore to avoid attacks where tokens are maliciously used as a scope label." is inconsistent with parts of the doc where we do use an underscore before a token.

Also https://datatracker.ietf.org/doc/html/draft-ietf-acme-scoped-dns-challenges-00 does do this.  

Also remove the:
> (TODO / DISCUSS: should we remove the underscore in-front of identifier-token per the guidance above?)

I'm almost wonder if we need to remove the "When placed in a domain name, the token MUST NOT start with an underscore to avoid attacks where tokens are maliciously used as a scope label."  or change it to be something different.

This may actually warrant some discussion on the list or in the session?

**Comment by moonshiner** [comment]
Agree this is a topic to bring up once the new version is published and perhaps discuss in person

**Comment by enygren** [comment]
Oops, we seem to have failed to discuss in-person this week (at least during the session).

**Comment by enygren** [comment]
The digicert mis-issuance incident has some context as to why we should always require the underscore in-front of a token and update accordingly:  https://www.digicert.com/support/certificate-revocation-incident

(I think this has good reasons as to why this should be a MUST, but with some caveats on the label colission risk.)
