### ISSUE TITLE
Clarify handling for string boundaries in the record

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#140]
From John Levine:
> It says to put everything in a text record which is fine, but it
> doesn't say anything about how to encode it. There are two competing
> approaches. One says that the string boundaries in the record don't
> matter, so combine all of the strings into one string. The other is to
> treat each string as a token or expression, and the string boundaries
> are the token or expression boundaries. The examples suggest the
> former way, but it should say so. Alternatively, people checking
> domain verification records need to say which way they're doing it.

Proposal would be to be explicit that within an RR the strings should be concatenated.

**Comment by moonshiner** [comment]
Suggested

In the paragraph for "### TXT Record "  
s/as in {{random-token}})./as in {{random-token}}). The random token should be treated as a concatenated string for the  RDATA ./
