### ISSUE TITLE
Handling of mismatching records in the RRset

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#141]
When an RRset has multiple records, we should clarify the handling for cases where some do not match.
I'd propose that we specify that validators MUST confirm that at least one matches and that validators MUST ignore all others (eg, garbage ones).

From John Levine:

> 2) If you put records at a tagged name that is supposed to be unique
and a query returns some junk records and some plausibly good records,
what do you do? Use what you can? Ignore it all because you probably
stepped on a wildcard?

**Comment by moonshiner** [comment]
I agree with this list conversation as well
