### ISSUE TITLE
"domain name" vs "owner name"

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#144]
From @wessels but likely needing more discussion:

> > either the RDATA or a domain name
> 
> > The RECOMMENDED format for a Validation Record's domain name is
> >
> 
> 
> Here and in numerous other places I think “domain name” might be better as “owner name”.  i.e.: "the owner name of a validation record"

**Comment by moonshiner** [comment]
At first I was thinking "domain owner name" but that seems a bit wonky. 

Then I wonder "should we define it specifically in the term section "Owner Name" ? 

there are 20 instances that I found of "domain name" so we'll want to walk through them

**Comment by moonshiner** [comment]
@wessels  so it was *this*your pull request went with?

**Comment by wessels** [comment]
Yes, essentially.  My comment about owner name was captured in #143 but Erik said he would open a separate issue for it (this one).

**Comment by ShivanKaul** [comment]
Can this issue be closed given https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/148?

**Comment by moonshiner** [comment]
yes
