### ISSUE TITLE
Domain verification for subtree under or just the domain

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#16]
Scope of verification:
Let's Encrypt - is only for the domain
Google - everything under that domain?

Call this out explicitly in the draft.

**Comment by Saklad5** [comment]
I'd say domain verification only proves that control of that exact RRset: any further interpretation is at the discretion of the provider.

**Comment by enygren** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-acme-dns-account-challenge-01 improves on this as well and we can reference it.

**Comment by moonshiner** [comment]
I believe it is now https://datatracker.ietf.org/doc/draft-ietf-acme-scoped-dns-challenges/ 

and it has an example ! yah

**Comment by moonshiner** [comment]
it is already referenced ACME-SCOPED-CHALLENGE in "Scope Indication" section
