### ISSUE TITLE
rename repo to draft draft-ietf-dnsop-domain-verification-techniques

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#27]
A nit, but i am a picker of nits

**Comment by ShivanKaul** [comment]
absolutely, will create a new version for the draft and will update the WG name then (to be accurate I guess)

**Comment by ShivanKaul** [comment]
Done! Also submitted renamed version to Datatracker, with an Appendix
