### ISSUE TITLE
Abstract mentions of RFCs' should not be references

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#32]
From idnits:

 ** The abstract seems to contain references ([RFC1034], [RFC1035]), which
     it shouldn't.  Please replace those with straight textual mentions of the
     documents in question.

Just refer to them as "RFC1034 and RFC1035"

**Comment by ShivanKaul** [comment]
Closed in https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/35
