### ISSUE TITLE
support simpler expiry syntax

### ISSUE THREAD

**Issue by paulwouters** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#43]
I think in general, this is too complicated and not required:

expiry=2023-02-08T02:03:19+00:00"

Can we also introduce an example and clarification with:

expiry=2023-02-08"

perhaps with a note saying it should be careful with timezones and eg not remove this until 2023-02-10 ? or otherwise perhaps state the issuer should take into account timezones when generating the record?

**Comment by ShivanKaul** [comment]
So have help text around timezones etc?

**Comment by moonshiner** [comment]
Two Things - 3339 has been updated by 9557 but 339 has the ABNF for "fulldate" which I feel many will use by default. 
full-date       = date-fullyear "-" date-month "-" date-mday

I think this should replace the more complex example.

**Comment by moonshiner** [comment]
https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/110

**Comment by moonshiner** [comment]
ready to close - thanks!
