### ISSUE TITLE
Relaying info from provider to consumer

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#46]
"In Section 3.1 you say "Consumers of the provider services need to relay information from a provider's website to their local DNS administrators". There are other ways to relay the information from provider to consumer, such as S/MIME, and the specification should reflect this."

**Comment by moonshiner** [comment]
This should be fleshed out by someone smarter than me.,

**Comment by enygren** [comment]
This does seem addressed in #118 although we might want to include something like "Where possible, APIs SHOULD be used to relay instructions." ?
