### ISSUE TITLE
Clarify use of underscore

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#47]
In 3.1 we say 

"The provider constructs the validation domain name by prepending a provider-relevant prefix followed by "-challenge" to the domain name being validated"

And then we use an underscore prefix in the example. We should clarify in the text as well that we should use an underscore.

**Comment by moonshiner** [comment]
I believe this one has been done, can be closed
