### ISSUE TITLE
Leveraging ACME challenges for other purposes

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#68]
(from Erik)

A related question worth considering:  when is it acceptable to leverage ACME challenge for other purposes?  For example, if moving a domain onto a CDN that is going to get a certificate for the domain prior to the migration but which also wants to validate that it is authorized for the domain to be transferred to it, when can the ACME challenge also be leveraged for both purposes?
I'm not sure we need to go into this, but perhaps it should be discussed.

**Comment by paulwouters** [comment]
Isn't this a regular case of "put record in DNS", except now the CDN provider relays the token to the user who asks their current DNS provider to add it? Eg I dont think from a protocol point of view, anything is different ?

**Comment by moonshiner** [comment]
Closing - seems like a tangent
