### ISSUE TITLE
Multi-provider / multi-CDN setups

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#69]
(from Erik)

A related and messier corner-case are multi-provider / multi-CDN setups.
For example, "foo.example.com" may CNAME to one of three different CDNs.
Each one of these needs to be able to manage a certificate and renew it every three months.
This likely applies to some of these other cases as well.  
I don't have good answers --- ACME doesn't handle this terribly well today --- 
but it is worth some thought as to how to handle.

**Comment by moonshiner** [comment]
I do believe this has been covered in the document.  someone confirms and close?

**Comment by moonshiner** [comment]
I believe this has been address and can be closed

**Comment by paulwouters** [comment]
I think so too.
