### ISSUE TITLE
Registry of labels?

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#74]
(from Erik)

I hate to ask it, but is there a need for a registry of _foo-challenge labels?
It seems like there could be potential security and operational risks
of multiple entities starting to use "_foo-challenge" for unrelated purposes.

**Comment by paulwouters** [comment]
We clarify how to make the label unique by including the entity's name, which presumably is fairly unique. We have the text:
```
Application owners SHOULD consult the IANA "Underscored and Globally Scoped DNS Node Names" registry {{UNDERSCORE-REGISTRY}} to confirm there are no collisions with existing entries.
```

I don't think anyone gains anything by adding their company name / brand in this registry as brands/companies are already fairly unique based on trademark rules. I propose to close this issue.
