### ISSUE TITLE
Account specific domain validation records

### ISSUE THREAD

**Issue by shuque** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#88]
Expand the treatment of DCV records to include a best practice for account specific validation records. The ACME DNS challenge is being enhanced for this purpose, and based on our feedback, they are adding an account specific label in front of the _acme-challenge label.

I am preparing a PR for this shortly.

**Comment by enygren** [comment]
I was just thinking about the "multi-CDN" handling, and was realizing that this could potentially address it depending on what you mean by "account" here.  For example, if each intermediary has a different account with the certificate authority then this would allow multiple _acme-challenge records to live side-by-side (eg, as "_acme-<RANDOMTOKEN1>-host-challenge.example.com").

I'd been thinking about a model of:

> 
> _acme-challenge IN TXT multi=1,2,4
> _1._acme-challenge IN CNAME <intermediate1-token>.dcv.provider1.example.
> _2._acme-challenge IN CNAME <intermediate2-token>.dcv.provider1.example.
> _4._acme-challenge IN CNAME <intermediate4-token>.dcv.provider1.example.
> 

but your approach might be less of a hack if I understand it right?

**Comment by shuque** [comment]
Yes, I agree the wildcard vs single label issue probably needs more discussion, and getting ACME updated to deal with that issue would be good.

The multi-CDN case is a bit orthogonal to the account specific identity case, although both cases could be in play together. For the account specific id case, we could potentially deal with multiple accounts in the same provider (we sometimes have to deal with that with AWS, where distinct AWS accounts operated by the same service need to be separately authorized for the same domain).

Here's the ACME account DNS challenge proposal: https://datatracker.ietf.org/doc/draft-ietf-acme-dns-account-challenge/

And the PR that they've now issued in response our feedback that the account id should be a label to the left, rather than a blob appended to _acme-challenge string:

https://github.com/aaomidi/draft-ietf-acme-dns-account-challenge/pull/25/files

I think we should have a separate section for the multi-CDN case.

**Comment by enygren** [comment]
On the acme-dns-account-challenge, opened for wildcard-vs-host:  https://github.com/aaomidi/draft-ietf-acme-dns-account-challenge/issues/29

The multi-CDN case is identical to what we're calling the "intermediary" case.  I guess the difference between the account and intermediary/multi-CDN use-cases is whether a TXT record is used directly, or if a CNAME to a TXT record is used.

**Comment by shuque** [comment]
Actually, I don't think that's necessarily a distinction. The account specific DCV record can also be delegated with a CNAME. You could have both account & multi-CDN based delegated DCV records.

So, this example authorized a specific account at a specific CDN ..

<accountstring>.<cdnstring>.<application>.<domain> CNAME <target-at-provider-that-has-a-TXT>

e.g.

ab623de5647f.cdn1._acme-challenge.example.com. IN CNAME abcd1234.foobar.cdn1.com.
abcd1234.foobar.cdn1.com. IN TXT "sjkldfjslk247ohdslfhsldfsdl27943o4"

etc.

**Comment by enygren** [comment]
Proposed a PR covering both of these cases in #95.
It doesn't reference draft-ietf-acme-dns-account-challenge in the appendix but perhaps should?
