### ISSUE TITLE
Recommendation for encoding in DNS labels

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#91]
We should have a recommendation of what encoding to use in DNS labels as base64 can be problematic there (due to the case sensitivity and due to the characters of "+", "/", and "=").  

Options seem to be:

1. base16 without any trailing "=" padding (which would need truncation of a 256-bit hash in order to be included along with other information in a DNS label)
2. base32 without the trailing "=" padding (which might still need truncation) 
3. either of these two options, leaving it up to the implementer to decide

While base32 is more compact, it is also more likely to include substrings that might trip up content filters.  Whether this is a problem could depend on context.

**Comment by shuque** [comment]
Yes, I agree we need to clarify the recommended alphabet here. I'm mulling over the options a bit and will circle back.

**Comment by enygren** [comment]
See #95 (which allows either)

**Comment by moonshiner** [comment]
The merged pull request does appear to address.
