### ISSUE TITLE
Interaction of CNAMEs with prepended attribute labels

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#92]
We recommend the use of prepended labels such as:
   _foo._bar-challenge.example.com
but also allow and give use-cases for where _bar-challenge.example.com could be a CNAME.
We should mention that in this case _bar-challenge.example.com must be a non-terminal (ie, MUST NOT be a zone cut and have NS records) even though records live underneath it.  For example while this may exist:
```
    _foo._bar-challenge.example.com IN TXT [...]
    _quux._bar-challenge.example.com IN CNAME [...]
    _bar-challenge.example.com IN CNAME [...]
```
_bar-challenge.example.com itself can't also have a TXT or NS record.

**Comment by moonshiner** [comment]
We should have some text on this.  Good catch sir.

**Comment by moonshiner** [comment]
Current examples in Section 5 (for my memory)

## TXT Record

_foo-challenge.example.com.  IN   TXT .....

_feature1._foo-challenge.example.com.  IN   TXT  .....

## CNAME Record

_foo-challenge.example.com.  IN   CNAME ....

-----

Then the text should go at the end of section 5.3 and should stand alone to make it obvious


If a CNAME record is being used for _foo-challenge.example.com. , then _foo-challenge.example.com. MUST NOT be a zone cut, and also can not also have any TXT or  NS records.

----

I was thinking of a way to show a bad example. but it does feel coim

**Comment by moonshiner** [comment]
https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/115

**Comment by moonshiner** [comment]
@enygren please take a look at this text in PR 115
