### ISSUE TITLE
Add atproto to examples

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#93]
It looks like "atproto" is using DNS TXT records for validating social media accounts, with BlueSky using this mechanism to authenticate users:

https://atproto.com/specs/handle#dns-txt-method

It may be worth adding this to the examples.

**Comment by moonshiner** [comment]
This does look relevant to add as an example.

**Comment by moonshiner** [comment]
https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/109
